Repository Evolutionary-Algorithms-On-Click/operations, pull requests merged in 2025-04, with the labels that each got.

#2 Initialize deployment ansible playbook for EvOC.
  .gitignore
  ansible/README.md
  ansible/inventory.ini
  ansible/playbook.yaml
  ansible/scripts/install-rabbitmq.sh
  ansible/templates/cockroachdb.service.j2
  ansible/templates/minio.default.j2
  ansible/templates/minio.service.j2
Labels: help wanted

#5 Updated Image tags in docker-compose
  docker/docker-compose.yml
Labels: enhancement

#7 Add healthcheck and update service images.
  docker/docker-compose.yml
Labels: enhancement

#9 Update healthcheck intervals and conditions in docker-compose
  docker/docker-compose.yml
Labels: bug, enhancement

#10 Update environment variable syntax for evolve_frontend
  docker/docker-compose.yml
Labels: enhancement
